server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-server
  cloud:
    config:
      enabled: false