server:
  port: 8090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: microservice-commandes
          uri: lb://microservice-commandes
          predicates:
            - Path=/api/commandes/**
        - id: microservice-produit
          uri: lb://microservice-produit
          predicates:
            - Path=/api/produits/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/